# .github/workflows/test-specific-parts.yml
name: Test Specific Parts (Lint on Push, Generate/Deploy Manually)

on:
  workflow_dispatch: # Para ejecución manual completa con inputs
    inputs:
      force_regenerate_test:
        description: 'Forzar regeneración para este test (ignora manifest)'
        required: false
        default: 'false'
        type: boolean
      test_language:
        description: "Idioma (ej. es). Requerido si char_key es letra/'0'. Opcional si char_key es dígito (para archivo)."
        required: false
        default: '' 
        type: string
      test_char_key:
        description: "Clave (letra, '0' para especiales, o dígito 'N' para books_N.csv)."
        required: false
        default: '5' # Para tu testeo de books_5.csv
        type: string
      log_level:
        description: 'Nivel de log para generate_static.py y app (INFO, DEBUG)'
        required: false
        default: 'DEBUG'
        type: choice
        options:
          - INFO
          - DEBUG
      deploy_test_slice:
        description: 'DESPLEGAR este slice a GitHub Pages (SOBREESCRIBIRÁ el sitio existente en la raíz)'
        required: false
        default: 'false'
        type: boolean
  push:
    branches:
      - 'main'

permissions:
  contents: write 
  pages: write    
  id-token: write 

jobs:
  test_lint_setup_only:
    name: Setup, Cache & Lint (Test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-test-specific-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-test-specific-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Lint with flake8
        run: |
          echo "Running Flake8 (strict pass for E9,F63,F7,F82)..."
          # flake8 . --count --select=E9,F63,F7,F82 --format=pylint --statistics
          echo "Running Flake8 (style and complexity pass)..."
          # flake8 . --count --format=pylint --statistics

  test_generate_specific_slice:
    name: Test Generate - Lang ${{ github.event.inputs.test_language || 'ALL' }} / CharKey ${{ github.event.inputs.test_char_key || 'NONE' }}
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: test_lint_setup_only
    
    env:
      GITHUB_PAGES_REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_PAGES_USERNAME: ${{ github.repository_owner }}
      SCRIPT_LOG_LEVEL: ${{ github.event.inputs.log_level }}
      FORCE_REGENERATE_FLAG_CMD: ${{ github.event.inputs.force_regenerate_test == 'true' && '--force-regenerate' || '' }}
      INPUT_LANG: ${{ github.event.inputs.test_language }}
      INPUT_CHAR_KEY: ${{ github.event.inputs.test_char_key }}
      # DEFAULT_LANG_FOR_FILTERS ya no es tan necesaria, el script lo maneja
      STATIC_SITE_OUTPUT_DIR_TEST_JOB: _test_site_slice

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-test-specific-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-test-specific-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Restore/Initialize Manifest (for testing)
        id: manifest_cache
        uses: actions/cache@v4
        with:
          path: .cache/generation_manifest.json
          key: ${{ runner.os }}-gen-manifest-test-slice-v7-${{ github.event.inputs.test_language }}-${{ github.event.inputs.test_char_key }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gen-manifest-test-slice-v7-${{ github.event.inputs.test_language }}-${{ github.event.inputs.test_char_key }}-
      - name: Initialize manifest if not restored by cache
        if: steps.manifest_cache.outputs.cache-hit != 'true'
        run: |
          echo "Test manifest not restored, creating empty."
          mkdir -p .cache
          echo "{}" > .cache/generation_manifest.json
        
      - name: Generate static site for specific slice
        env:
          STATIC_SITE_OUTPUT_DIR: ${{ env.STATIC_SITE_OUTPUT_DIR_TEST_JOB }}
        run: |
          set -e
          COMMAND_ARGS=""
          
          if [[ -n "$INPUT_LANG" ]]; then
            COMMAND_ARGS="$COMMAND_ARGS --language $INPUT_LANG"
          fi
          
          if [[ -n "$INPUT_CHAR_KEY" ]]; then
            COMMAND_ARGS="$COMMAND_ARGS --char-key $INPUT_CHAR_KEY"
          fi
          
          echo "Output directory for script: $STATIC_SITE_OUTPUT_DIR"
          echo "Running: python generate_static.py $COMMAND_ARGS $FORCE_REGENERATE_FLAG_CMD --log-level ${{ env.SCRIPT_LOG_LEVEL }}"
          python generate_static.py $COMMAND_ARGS $FORCE_REGENERATE_FLAG_CMD --log-level ${{ env.SCRIPT_LOG_LEVEL }}
          echo "Static site generation finished. Output in $STATIC_SITE_OUTPUT_DIR"

      - name: Debug Paths and Variables
        if: always()
        run: |
          echo "--- Debug Information ---"
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "STATIC_SITE_OUTPUT_DIR_TEST_JOB: ${{ env.STATIC_SITE_OUTPUT_DIR_TEST_JOB }}"
          echo "pwd: $(pwd)"
          echo "--- End Debug ---"
      - name: List generated files (for debugging)
        if: always()
        run: |
          echo "Contenido de ${{ github.workspace }}/${{ env.STATIC_SITE_OUTPUT_DIR_TEST_JOB }}:"
          ls -Rahl ${{ github.workspace }}/${{ env.STATIC_SITE_OUTPUT_DIR_TEST_JOB }} || echo "Dir no existe."
          echo "--- Fin listado ---"
      - name: Upload specific slice artifact (for inspection)
        uses: actions/upload-artifact@v4
        with:
          name: test-site-slice-${{ env.INPUT_LANG || 'all_langs' }}-${{ env.INPUT_CHAR_KEY || 'all_chars_or_datafile' }}
          path: ${{ env.STATIC_SITE_OUTPUT_DIR_TEST_JOB }}/
          if-no-files-found: error 
          retention-days: 1
      - name: Deploy Test Slice to GitHub Pages (IF ENABLED)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_test_slice == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.STATIC_SITE_OUTPUT_DIR_TEST_JOB }}
          keep_files: false
          allow_empty_commit: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy test slice for Lang ${{ env.INPUT_LANG || 'ALL' }}/CharKey(FileOrAuthor) ${{ env.INPUT_CHAR_KEY || 'NONE' }} (Run ID ${{ github.run_id }})
