# .github/workflows/test-specific-parts.yml
name: Test Specific Parts (Lint on Push, Generate/Deploy Manually) # Nombre actualizado

on:
  workflow_dispatch: # Para ejecución manual completa con inputs
    inputs:
      force_regenerate_test:
        description: 'Forzar regeneración para este test (ignora manifest)'
        required: false
        default: 'false'
        type: boolean
      test_language:
        description: 'Idioma para testear generación (ej. es, en).'
        required: false
        default: 'es'
        type: string
      test_char_key:
        description: 'Clave de carácter para testear generación (ej. z, a, 0).'
        required: false
        default: 'z'
        type: string
      log_level:
        description: 'Nivel de log para generate_static.py (INFO, DEBUG)'
        required: false
        default: 'INFO'
        type: choice
        options:
          - INFO
          - DEBUG
      deploy_test_slice: # NUEVO INPUT PARA CONTROLAR EL DESPLIEGUE
        description: 'DESPLEGAR este slice a GitHub Pages (SOBREESCRIBIRÁ el sitio existente)'
        required: false
        default: 'false' # Por defecto, NO desplegar
        type: boolean
  push:
    branches:
      - 'large-data-optimization'

permissions:
  contents: write # Necesario para peaceiris/actions-gh-pages si pushea a una rama
  pages: write    # Necesario si se despliega a través del artefacto de GitHub Pages
  id-token: write # A menudo necesario para acciones de despliegue seguras

jobs:
  test_lint_setup_only:
    name: Setup, Cache & Lint (Test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-test-specific-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-test-specific-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Lint with flake8
        run: |
          echo "Running Flake8 (strict pass for E9,F63,F7,F82)..."
          flake8 . --count --select=E9,F63,F7,F82 --format=pylint --statistics || exit 1
          echo "Running Flake8 (style and complexity pass)..."
          # flake8 . --count --format=pylint --statistics

  test_generate_specific_slice:
    name: Test Generate & Deploy (Manual) - Lang ${{ github.event.inputs.test_language }} / Char ${{ github.event.inputs.test_char_key || 'ALL' }}
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: test_lint_setup_only
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-test-specific-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-test-specific-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore/Initialize Manifest (for testing)
        id: manifest_cache
        uses: actions/cache@v4
        with:
          path: .cache/generation_manifest.json
          key: ${{ runner.os }}-gen-manifest-test-slice-v1-${{ github.event.inputs.test_language }}-${{ github.event.inputs.test_char_key }}
      
      - name: Initialize manifest if not restored by cache
        if: steps.manifest_cache.outputs.cache-hit != 'true'
        run: |
          echo "Test manifest not restored from cache, creating empty for this job."
          mkdir -p .cache
          echo "{}" > .cache/generation_manifest.json
        
      - name: Generate static site for specific slice
        env:
          FORCE_REGENERATE_FLAG: ${{ github.event.inputs.force_regenerate_test == 'true' && '--force-regenerate' || '' }}
          TARGET_LANG: ${{ github.event.inputs.test_language }}
          TARGET_CHAR_KEY: ${{ github.event.inputs.test_char_key }}
        run: |
          set -e
          COMMAND_ARGS=""
          if [[ -n "$TARGET_LANG" ]]; then
            COMMAND_ARGS="$COMMAND_ARGS --language $TARGET_LANG"
            if [[ -n "$TARGET_CHAR_KEY" ]]; then
              COMMAND_ARGS="$COMMAND_ARGS --char-key $TARGET_CHAR_KEY"
            fi
          else
            echo "TARGET_LANG está vacío, se intentará generar para todos los idiomas."
          fi
          echo "Running: python generate_static.py $COMMAND_ARGS $FORCE_REGENERATE_FLAG"
          python generate_static.py $COMMAND_ARGS $FORCE_REGENERATE_FLAG
          echo "Static site generation for specific slice finished."

      - name: List generated files in _site (for debugging)
        if: always()
        run: |
          echo "Contenido de _site:"
          ls -R _site || echo "_site no existe o está vacío."

      - name: Upload specific slice artifact (for inspection)
        uses: actions/upload-artifact@v4
        with:
          name: test-site-slice-${{ github.event.inputs.test_language || 'all_langs' }}-${{ github.event.inputs.test_char_key || 'all_chars' }}
          path: _site/
          if-no-files-found: error 
          retention-days: 1

      # --- NUEVO PASO DE DESPLIEGUE ---
      - name: Deploy Test Slice to GitHub Pages (IF ENABLED)
        # Solo se ejecuta si es workflow_dispatch Y el input deploy_test_slice es 'true'
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_test_slice == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # ATENCIÓN: Esto sobreescribirá el contenido de tu rama gh-pages (o el despliegue de Actions)
          # con el contenido de ./_site de este testeo parcial.
          # Considera usar un 'target_branch' diferente o 'destination_dir' si quieres aislarlo.
          # Ejemplo para pushear a una subcarpeta (requiere que tu sitio maneje la URL base):
          # destination_dir: ./test-previews/${{ github.event.inputs.test_language }}-${{ github.event.inputs.test_char_key || 'allchars' }}
          # keep_files: true # Podría ser útil si usas destination_dir para no borrar otros previews
          # allow_empty_commit: false # Evitar commits vacíos si no hay cambios
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy test slice for ${{ github.event.inputs.test_language }}/${{ github.event.inputs.test_char_key || 'ALL' }}
